name: "CodeQL"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 18 * * 1'

jobs:
  analyze:
    name: Analyze
    runs-on: [self-hosted, linux, X64]
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
#         config-file: ./.github/config/code-scanning.yml
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
#         external-repository-token: ${{ secrets.GITHUB_TOKEN }}
#below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
