name: Sync issue to Azure DevOps work item

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Testing workflow
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.AZURE_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.PERSONAL_TOKEN }}"
          ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
          ado_project: '${{ secrets.ADO_PROJECT }}'
          ado_wit: 'GitHub Issues' 
          ado_new_state: 'New'
          ado_close_state: 'Closed'
          ado_active_state: 'Active'  
          ado_bypassrules: true
          log_level: 100
