name: Sync Pull Request to Azure Boards

on:
  pull_request:
    types: [opened, edited, closed]
    branches:
      - master

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Running Workflow
    steps:
    - uses: danhellem/github-actions-pr-to-work-item@master
      env:
        ado_token: '${{ secrets.AZURE_PERSONAL_ACCESS_TOKEN }}'   
        github_token: '${{ secrets.PERSONAL_TOKEN }}'    
        ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
        ado_project: '${{ secrets.ADO_PROJECT }}'
        ado_wit: 'GitHub Pull Request' 
        ado_new_state: 'New'
        ado_active_state: 'Active'
        ado_close_state: 'Closed'
